//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int IDServices { get; set; }
        public int ReceiptNumber { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.DateTime Date { get; set; }
        public int IDClient { get; set; }
        public int IDList { get; set; }
        public int IDMaster { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
